name: atlas
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  file_selector: ^1.0.3
  open_file: ^3.5.9
  excel: ^4.0.6 
  path_provider: ^2.1.5
  shared_preferences: ^2.2.2
  english_words: ^4.0.0
  provider: ^6.0.0
  file_saver: ^0.2.14


dev_dependencies:
  build_runner: ^2.4.15 
  build_web_compilers: ^4.1.1 
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0 

flutter:
  uses-material-design: true

  assets:
    - assets/images/atlas_login.png
    - assets/images/inicio.jpg
    - assets/images/Nestle.jpeg
